{% set name = "pvl" %}
{% set version = "1.3.2" %}
{% set sha256 = "7d07baa88af26d2ff04a3548a54392de3245dea13f23d964dc8ed725a5efc6a2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6

test:
  imports:
    - pvl

about:
  home: http://github.com/planetarypy/pvl
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python implementation of PVL (Parameter Value Language)

  description: |
    PVL is a markup language, similar to xml, commonly employed for entries in
    the Planetary Database System used by NASA to store mission data, among other
    uses. This package supports both encoding a decoding a superset of PVL,
    including the USGS Isis Cube Label and NASA PDS 3 Label dialects.
  doc_url: http://pvl.readthedocs.org
  dev_url: https://github.com/planetarypy/pvl

extra:
  recipe-maintainers:
    - rbeyer
