travis:
  secure:
    BINSTAR_TOKEN: IuvpsDxqUxDwXkT/5LIsBwoBjzlRxWjPCkGHgyEhcIswYiDaNpuuSLwMbo0Wi7eKv72K5zAhkf2OckwVUz0/2aQeDKQl1agvBS9+q16YjPd2j9ljiK1tRZY7NLuA6dQO4CkUQfQzvhE6rbg+bvYN6M+fFnXlRuB5pkYlOV9hGbwSp3EacFv/rmy6NqvjuQB74e93i+RRp3LUSkURy+8gCYm9neXvZFYVB7m+iFTVlXNnnrFgKn5HBfTTXY1ZwnOu8Rjq2JXhUarCMjHueCpI7ocjUKVN+ADqozeAXS5R8izrvB+023uR46mBfPqRF2j3AM4V/Eal/JW/XvF8A2MiMQoZpxelt8s+TevxYlHNjqIEV/IuZZRKRe1rcS3D9dT0TaL7/+KjjQi531MUw2HwIvJjtl3iYM0d5qGm7IG7dZ52VhbJaR0t5IHA01KJJreG1/q4pjNKsp6Iu9/b5ZWUD5+27W/wYxjFIjTivY+Ucmi+jMIdfFLgPqaGMkfiZXH5/BfiyDy6kS0GFSQ8h4v8xquOK4XcPzsxpmnvZYLV2rmuhDZBv/q6McO+VVXKY08xDNEmZzPstESg9/13dHMDBDBJtn36m0v5V6JQ9iwAva0inKyVC95MwhAfhHynFFzCLixR1DHeXqwB+6kjXn6ZqFeJ2qlg7vfJtQnXobwfam0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
