travis:
  secure:
    BINSTAR_TOKEN: REqMZgqMd6L2q0vVkPl9DyMhC3yxQil6drcZ6kCKv/YUdTHyVC2tbwhhrxexn9AMPYm3UBvoZnVwaJepN9vxADnnEU1MS/Ac4/jxcGXJxFVy7eeyp3NFsR4W0S9pYPCBMmdsT8euIHCfd+v43OCBhXKEDU6BbwERHR+1sgf2pVCSWtxvTREeGZX7Wue9qj0zwkyhRI4zwbbnFYo/tVWhBXHz5mXIHl45L/wAUOevm0TtJnJkawehduoxdA9apLTY0LtIHQazlAwyQpT6z6qFwihICr5+c/InLnCIAwC+iS3f4wV14orfzbBFihSCw9AVM9tcg6kJUrzE4cOB9mGtPTJE1KA6fG1hv+OgokV6fTgw5ZdJS3dMLt+o4B3g4G6jjzQwWDHbrQEEK9dEpMaQCC/S9kgFJhG2gDh9xahVuPuCLWgbgD5GWyNkRhR/ydXX8GkGvv15zVK0Mn9tIK4HJsj4N+G3j/3m/QfU0kTSBCQtSJ5Twu/+4ue4KthZYSd/G5gSHQ9LhHJLkCxBj5vDtkz0Jsyu4IV3Zdqgdgc1U23DtqH8LI8uIKMbSFsl9FKDOB10AI78BAfemj5l/jk1tMfFY1vGUwjjyyVhscINzgh5Mt9bgTE536MPITDxgrdE5f6LnYX0a0k3Vg7HqpL6g9HZ8/hSM243w7aao97ECv0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
